### ISSUE TITLE
The test results of CDR reported in your paper use test_filter.data or test.data as evaluation input?

### ISSUE THREAD

**Issue by nefujiangping** [fenchri/edge-oriented-graph#10]
It seems that hypernym filtering has compact to the final results.

**Comment by fenchri** [comment]
Yes, as mentioned in the paper we applied hypernym filtering to the train, dev and test sets similar to [Verga et al. (2018)](https://www.aclweb.org/anthology/N18-1080.pdf).

**Comment by nefujiangping** [comment]
Oh, I got it. Thanks.

**Comment by JohnGiorgi** [comment]
Hi @fenchri, 

Do you have the results for a model trained _without_ hypernym filtering listed anywhere? I am interested in how much it impacts the performance of the final model. Thanks!

**Comment by fenchri** [comment]
Hi there!

Apologies, but I do not have solid numbers to show you, since for an apple-to-apple comparison I tried to have the same setting as previous work.

However, I did experiment with that when I first started this work and I found that performance dropped at least 1% *without* hypernym filtering.
I would recommend to re-run the code by changing the pre-processing to not include the filtering if you need exact numbers, but I could tell that from a very early, toy experimentation, performance should be quite lower.

Hope that helps, cheers :)

**Comment by JohnGiorgi** [comment]
Thanks a lot @fenchri :) 

Also, does the filtering only apply to disease entities? Or does it also apply to chemicals?

**Comment by fenchri** [comment]
Hey! Terribly sorry for the late reply!

The filtering goes by disease if I remember correctly, but ultimately the entire chemical-disease pair gets dropped. In this paper, we kept all entities but simply did not classify the filtered pairs.

This [script](https://github.com/fenchri/edge-oriented-graph/blob/master/data_processing/filter_hypernyms.py) is responsible for the filtering process :)
